---
title: "Quantile Regression"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("../theme/theme-mooc.R")
```

```{r, flcolours=TRUE}
library(ismev)
library(quantreg)
data(wavesurge)
par(mar=c(5.1,4.1,2.1,2.1))
plot(wavesurge, xlab="Wave height [m]", ylab="Surge [m]")
taus <-  seq(0.05,0.95, by=0.05)
qrm <- rq(wavesurge$surge~wavesurge$wave,tau=taus)
beta <- coef(qrm)
select <- c(2,5,10,15,18)
cols <- c(4,3,2,3,4)
for (i in seq_along(select)) {
    beta <- coef(qrm)[,select[i]]
    abline(beta, col=cols[i], lwd=2)
    corners = par("usr") 
    par(xpd = TRUE) 
    text(x = corners[2]+.1, y = beta[1]+beta[2]*corners[2] , paste0(100*taus[select[i]],"%"), srt = 0, adj=c(0,0.5), col=cols[i])
    par(xpd=FALSE)
}
```

```{r, flcolours=TRUE}
library(ismev)
library(quantreg)
data(wavesurge)
par(mar=c(5.1,4.1,2.1,2.1))
plot(wavesurge, xlab="Wave height [m]", ylab="Surge [m]", type="n")
beta <- coef(rq(wavesurge$surge~wavesurge$wave,tau=0.9))
polygon(c(7,7,8,8),c(par()$usr[4], beta[1]+beta[2]*c(7,8), par()$usr[4]),col=grey(0.9), border=NA, density=30)
text(7.5,par()$usr[3], "90%", cex=1.5, col=grey(0.7), adj=c(0.5,-0.1))
text(7.5,par()$usr[4], "10%", cex=1.5, col=grey(0.7), adj=c(0.5,1.1))
polygon(c(7,7,8,8),c(par()$usr[3], beta[1]+beta[2]*c(7,8), par()$usr[3]),col=grey(0.9), border=NA, density=30, angle=305)
points(wavesurge)
taus <-  seq(0.05,0.95, by=0.05)
qrm <- rq(surge~wave, data=wavesurge, tau=taus)
beta <- coef(qrm)
select <- c(2,5,10,15,18)
cols <- c(4,3,2,3,4)
for (i in seq_along(select)) {
    beta <- coef(qrm)[,select[i]]
    abline(beta, col=cols[i], lwd=2)
    corners = par("usr") 
    par(xpd = TRUE) 
    text(x = corners[2]+.1, y = beta[1]+beta[2]*corners[2] , paste0(100*taus[select[i]],"%"), srt = 0, adj=c(0,0.5), col=cols[i])
    par(xpd=FALSE)
}

```
```{r}
plot(summary(qrm), parm="(Intercept)", ols=FALSE)
points(taus[select], coef(qrm)[1,select], col=cols, pch=16)
abline(v=taus[select], col=cols, lty=3)
```
```{r}
plot(summary(qrm), parm="wave", ols=FALSE)
points(taus[select], coef(qrm)[2,select], col=cols, pch=16)
abline(v=taus[select], col=cols, lty=3)
```
